<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Dafny/WrappedModule.cs"
             Link="Generated/WrappedModule.cs" />

    <Compile Include="../Dafny/TaxonAdapter.cs"
             Link="Generated/TaxonAdapter.cs" />

    <Compile Include="../Dafny/ObservationAdapter.cs"
             Link="Generated/ObservationAdapter.cs" />
</ItemGroup>

<ItemGroup>
    <Reference Include="DafnyRuntime">
        <HintPath>/opt/homebrew/Cellar/dafny/4.11.0/libexec/net8.0/DafnyRuntime.dll</HintPath>
    </Reference>
</ItemGroup>
</Project>
