name: .NET Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install SQLite
      run: sudo apt-get update && sudo apt-get install -y sqlite3
    - name: Create test database
      run: |
        sqlite3 /tmp/bison.db < data/schema.sql
        sqlite3 /tmp/bison.db < data/dump.sql

    - name: Verify database
      run: sqlite3 /tmp/bison.db ".tables"

    - name: Test
      env:
        BISONDBPATH: /tmp/bison.db
      run: dotnet test --no-build --verbosity normal