#workflow name on GithUb
name: Label issues

on: #Defines when workflow should start
  issues: #runs workflow when something happens to an issue
    types: [opened,closed]

permissions: #what the workflow is allowed to change
  issues: write

jobs: #defines the work that workflow should perform
  label-new:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Add new-issue label
        uses: actions/github-script@v7
        with: 
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number, 
              labels: ['new-issue']
            })
  label-closed:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Add label for closed issues
        uses: actions/github-script@v7
        with: 
          script: |
            github.rest.issues.removeLabel({ //Removes label saying 'new-issue'
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'new-issue'
            })
            github.rest.issues.addLabels({ //adds label saying 'finished'
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number, 
              labels: ['finished']
            })
            

